zeus-member-mgmt:
  api:
    version: 1.0.0
server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/membermgmtdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: membermgmtapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    # bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: zeus-member-mgmt-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  flyway:
    user: membermgmtadmin
    password: password
    clean-disabled: false
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/membermgmt.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


